[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
NFLData = "38e18452-fdda-4cae-b91e-088906595f57"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
